name: AI Code Review
on: pull_request

jobs:
  code_review:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write    
    steps:
      - uses: actions/checkout@v3
      - name: AI Code Review
        uses: Mamo-00/Code-Patrol@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LLAMA_API_KEY: ${{ secrets.LLAMA_API_KEY }}
